### ISSUE TITLE
Gracefully handle broken session factory

### ISSUE THREAD

**Issue by ralphbean** [bbangert/velruse#105]
Say your app is using a cookie based session factory and the user has cookies disabled on their browser, then the following code raises a CSRFError:

``` python
        if request.GET.get('state') != request.session.get('state'):
            raise CSRFError(
                'CSRF Validation check failed. Request state %s is not '
                'the same as session state %s' % (
                    request.GET.get('state'), request.session.get('state')))
```

`request.session.get('state')` will always be `None` for this user.  This results in a 500 error when they try to login.
- Is a there a recommended way of catching that error and handling it nicely?
- If not, is this a bug?

**Comment by avanov** [comment]
`if request.GET.get('state') != request.session.get('state')`
This code no longer exists since it has been changed due to  CSRF vulnerability (see more at #98).

Also, it shouldn't be considered as a bug, because you can (and probably have to) define custom exception view for your pyramid application (see more at #101) in order to handle exceptions from velruse.

**Comment by mmerickel** [comment]
Velruse in its current form requires a cookie based session. We can
consider ways around this but I personally don't consider it a priority
because Velruse is targeting end users and not apis.

**Comment by ralphbean** [comment]
Ah, the exception view in #101 is what I was looking for.  Thanks!  I'll close this issue.
